Fixes parallel tests with JAR deployment and helps debugging of parallel builds
arquillian/arquillian-core pull request #306
Opened 2021-01-29 22:39 UTC by lprimak

Feature:
- Support parallel testing in JAR deployments by making generated WAR name UUID rather than "test.war"

Bugs:
- catch IOException in remote extension loader and throw appropriate error rather than swallowing the exception

Fixes #304
Fixes #305

2021-02-06 19:34 UTC, bartoszmajsak requested changes
Thank you very much for this improvement! Much appreciated. 

I just have two minor suggestions and we can merge it.

Please update the branch to the latest `master` or let me edit this PR so I can take care of it :)

2021-02-06 19:34 UTC, bartoszmajsak commented on protocols/servlet-jakarta/src/main/java/org/jboss/arquillian/protocol/servlet5/v_5/ServletProtocolDeploymentPackager.java
> +            ShrinkWrap.create(WebArchive.class, UUID.randomUUID().toString() + ".war")
```suggestion
            ShrinkWrap.create(WebArchive.class, "test-" + UUID.randomUUID().toString() + ".war")
```

I would keep `test-` prefix at least. This way it's more obvious what this archive could be.

2021-02-06 19:34 UTC, bartoszmajsak commented on protocols/servlet/src/main/java/org/jboss/arquillian/protocol/servlet/v_3/ServletProtocolDeploymentPackager.java
> +            ShrinkWrap.create(WebArchive.class, UUID.randomUUID().toString() + ".war")
```suggestion
            ShrinkWrap.create(WebArchive.class, "test-" + UUID.randomUUID().toString() + ".war")
```

Same reason as above.

2021-02-06 20:24 UTC, lprimak commented
@bartoszmajsak all done!

2021-02-06 20:38 UTC, bartoszmajsak approved these changes

2021-02-06 20:38 UTC, bartoszmajsak commented
Awesome, thank you!

2021-02-06 20:39 UTC, merged

2021-03-01 19:31 UTC, arjantijms commented
Hey nice to see this finally being done! @lprimak is this from the issue I created years ago, or did the same problem just happen to bubble up again?

2021-03-01 19:36 UTC, lprimak commented
Probably the same issue you had, but independently noticed :)