Fix for #323 JUnit5 @Nested tests - ClassNotFoundException
arquillian/arquillian-core pull request #324
Opened 2021-03-08 18:08 UTC by rimuln

#### Short description of what this resolves:
Solves ClassNotFoundException for nested test classes

#### Changes proposed in this pull request:
replaced selector for discovery
added test case for succesfull test in nested class

2021-03-08 18:17 UTC, rimuln commented
hmm. circleci failed but details are:
Arquillian Core Implementation Base ................ FAILURE [  1.665 s]
I think that not related to this PR. At my machine build was success

2021-03-09 16:35 UTC, bartoszmajsak requested changes
Thanks for this fix! I have just a tiny little fix in the test method name as a suggestion which you can apply right away.

2021-03-09 16:35 UTC, bartoszmajsak commented on junit5/container/src/test/java/org/jboss/arquillian/junit5/container/JUnitJupiterTestRunnerTestCase.java
> +  public void shouldNotReturnExceptionToClientIfAsumptionPassingInNestedClass() throws Exception {
```suggestion
  public void shouldNotReturnExceptionToClientIfAssumptionIsPassingInNestedClass() throws Exception {
```

2021-03-10 07:44 UTC, rimuln commented
I'm not sure what do now. request change was accepted and commited

2021-03-17 13:59 UTC, bartoszmajsak approved these changes

2021-03-17 14:00 UTC, merged